# 应用名
spring. application.name: config-server
# 存储配置文件的git地址
spring.cloud.config.server.git.uri: https://github.com/yukaiji/springcloud-app-config
# git用户名
spring.cloud.config.server.git.username: root
# git密码
spring.cloud.config.server.git.password: 123456
# 启动端口号
server.port: 9001
# 注册到eureka上
eureka.client.serviceUrl.defaultZone: http://eurekaserver1:1111/eureka/
